---
title: "modeling"
author: "Alisson Rosa e Vítor Pereira"
abstract: "One Piece > Naruto"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
geometry: left=1.7cm, right=1.7cm, top=2.5cm, bottom=2.2cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true
---

```{r setup, include=FALSE}
options(digits = 3) # Arrendodamento
ggplot2::theme_set(ggplot2::theme_minimal()) # Tema dos gráficos produzidos no ggplot2
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.pos = "H", fig.align = "center", fig.width = 7.8, fig.height = 3.7)
# devtools::install_github("https://github.com/AlissonRP/mypdf1") remova o `#`

library(tidyverse)
library(tidymodels)
library(modeltime)
library(forecast)
library(sknifedatar)
```

```{r}
df <- read_csv("naruto.csv")
```

```{r}
splits <- initial_time_split(df, prop=0.8)
df_train=training(splits)
df_test=testing(splits)
initial_time_split(df, prop = 0.8) %>%
  timetk::tk_time_series_cv_plan() %>%
  timetk::plot_time_series_cv_plan(as.Date(Time), rate, .interactive = FALSE,
                           .title = "Avaliação de Naruto Shippuden dados de Treino / Teste") +
  theme(strip.text = element_blank())
```

```{r}
recipe_base <- recipe(rate~Time, data=df)

recipe_date_features <- recipe_base %>% 
  step_date(Time, features = c('month','year'))

recipe_date_extrafeatures <- recipe_date_features %>% 
  step_date(Time, features = c('quarter','semester'))
       
recipe_date_extrafeatures_lag <- recipe_date_extrafeatures %>% 
  step_lag(rate, lag = 1:6) %>% 
  timetk::step_ts_impute(all_numeric(), period=365)
  
recipe_date_extrafeatures_fourier<-recipe_date_extrafeatures  %>% 
  timetk::step_fourier(Time, period = 365/12, K = 1)
```

```{r}
prophet_boost <- prophet_boost(mode = 'regression') %>% 
  set_engine("prophet_xgboost")

prophet_boost_log <- prophet_boost(
    mode = 'regression',
    changepoint_range = 0.8,
    logistic_floor = min(df$rate),
    logistic_cap = max(df$rate),
    growth = 'logistic'
  ) %>%
  set_engine("prophet_xgboost")

#mars <- mars(mode = 'regression') %>% 
#  set_engine('earth') #precisa do pacote "earth"

#auto_arima_boost <- arima_boost() %>% 
#  set_engine('arima_xgboost')

#arima_boost <- arima_boost(
#    tree_depth = 6,
#    learn_rate = 0.1
#) %>%
#    set_engine(engine = "arima_xgboost")
ets <- exp_smoothing() %>%
  set_engine('ets')
etsMMM <- exp_smoothing(error = "multiplicative",trend = "multiplicative",season = "multiplicative") %>%
    set_engine("ets")
etsMAM <- exp_smoothing(error = "multiplicative",trend = "additive",season = "multiplicative")  %>%
    set_engine("ets")
croston <- exp_smoothing() %>%
    set_engine("croston")
theta <-  exp_smoothing() %>%
    set_engine("theta")
smooth_es_AAM <-exp_smoothing(
  error = "additive",
  trend = "additive",
  season = "multiplicative"
) %>%
    set_engine("smooth_es")
smooth_es_AAA <- exp_smoothing(
  error = "additive",
  trend = "additive",
  season = "additive"
) %>%
  set_engine("smooth_es")
smooth_es_MAM <- exp_smoothing(
  error = "multiplicative",
  trend = "additive",
  season = "multiplicative"
) %>%
  set_engine("smooth_es")
etsAAA <- exp_smoothing(error = "additive",trend = "additive",season = "additive") %>%
    set_engine("ets")
ets_auto <- exp_smoothing(error = "auto",trend = "auto",season = "auto") %>%
    set_engine("ets")
```

```{r}
model_work <- workflow_set(
  preproc = list(
    base                  = recipe_base,
    features              = recipe_date_features, 
    extrafeatures         = recipe_date_extrafeatures,
    extrafeatures_lag     = recipe_date_extrafeatures_lag,
    extrafeatures_fourier = recipe_date_extrafeatures_fourier
  ),
  models  = list(
    #M_auto_arima_boost       = auto_arima_boost,
    M_prophet_boost_log = prophet_boost_log, 
    M_prophet_boost     = prophet_boost,
    #M_mars              = mars,
    #M_arima_boost       = arima_boost,
    M_ets               = ets,
    M_etsMMM            = etsMMM, 
    M_etsMAM            = etsMAM,
    M_croston           = croston,
    M_theta             = theta,
    M_smoothAAM         = smooth_es_AAM, 
    M_smoothAAA         = smooth_es_AAA,
    M_smoothMAM         = smooth_es_MAM,
    M_etsAAA            = etsAAA, 
    M_etsauto           = ets_auto 
    #M_etsAAM            = etsAAM
  ),
  cross   = TRUE
)
model_work <- model_work %>% anti_join(
    tibble(wflow_id = c("extrafeatures_lag_M_mars")), 
            by = "wflow_id")
model_fit <- modeltime_wfs_fit(.wfsets = model_work, 
                            .split_prop = 0.8, 
                            .serie=df)
model_fit
model_metrics <- modeltime_wfs_rank(model_fit,
                              rank_metric = "rmse")
model_metrics %>%
  select(-`.fit_model`) %>%
  mypdf1::pdf1_tbl("Métricas")
```

```{r}
modeltime_wfs_forecast(.wfs_results = model_fit, 
                       .serie = df, 
                       .split_prop=0.8) %>% 
  plot_modeltime_forecast(.interactive=FALSE)
```

```{r}
etsANN <- exp_smoothing(error = "additive",trend = "none",season = "none") %>%
    set_engine("ets")
etsANA <- exp_smoothing(error = "additive",trend = "none",season = "additive") %>%
    set_engine("ets")
etsANM <- exp_smoothing(error= "additive",trend = "none",season = "multiplicative") %>% set_engine("ets")
etsAANN <- exp_smoothing(error = "additive",trend = "additive",season = "none", damping = 'none') %>%
    set_engine("ets")
etsAAND <- exp_smoothing(error = "additive",trend = "additive",season = "none", damping = 'damped') %>%
    set_engine("ets")
etsAAAN <- exp_smoothing(error = "additive",trend = "additive",season = "additive", damping = 'none') %>%
    set_engine("ets")
etsAAAD <- exp_smoothing(error = "additive",trend = "additive",season = "additive", damping = 'damped') %>%
    set_engine("ets")
etsAAMN <- exp_smoothing(error = "additive",trend = "additive",season = "multiplicative", damping = 'none') %>%
    set_engine("ets")
etsAAMD <- exp_smoothing(error = "additive",trend = "additive",season = "multiplicative", damping = 'damped') %>%
    set_engine("ets")
etsAMNN <- exp_smoothing(error = "additive",trend = "multiplicative",season = "none", damping = 'none') %>%
    set_engine("ets")
etsAMND <- exp_smoothing(error = "additive",trend = "multiplicative",season = "none", damping = 'damped') %>%
    set_engine("ets")
etsAMAN <- exp_smoothing(error = "additive",trend = "multiplicative",season = "additive", damping = 'none') %>%
    set_engine("ets")
etsAMAD <- exp_smoothing(error = "additive",trend = "multiplicative",season = "additive", damping = 'damped') %>%
    set_engine("ets")
etsAMMN <- exp_smoothing(error = "additive",trend = "multiplicative",season = "multiplicative", damping = 'none') %>%
    set_engine("ets")
etsAMMD <- exp_smoothing(error = "additive",trend = "multiplicative",season = "multiplicative", damping = 'damped') %>%
    set_engine("ets")
etsMNN <- exp_smoothing(erro = "multiplicative",trend = "none",season = "none") %>%
  set_engine("ets")
etsMNA <- exp_smoothing(erro = "multiplicative",trend = "none",season = "additive") %>%
  set_engine("ets")
etsMNM <- exp_smoothing(error= "multiplicative",trend = "none",season = "multiplicative") %>% set_engine("ets")
etsMANN <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "none", damping = 'none') %>%
  set_engine("ets")
etsMAND <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "none", damping = 'damped') %>%
  set_engine("ets")
etsMAAN <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "additive", damping = 'none') %>%
  set_engine("ets")
etsMAAD <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "additive", damping = 'damped') %>%
  set_engine("ets")
etsMAMN <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "multiplicative", damping = 'none') %>%
  set_engine("ets")
etsMAMD <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "multiplicative", damping = 'damped') %>%
  set_engine("ets")
etsMMNN <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "none", damping = 'none') %>%
  set_engine("ets")
etsMMND <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "none", damping = 'damped') %>%
  set_engine("ets")
etsMMAN <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "additive", damping = 'none') %>%
  set_engine("ets")
etsMMAD <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "additive", damping = 'damped') %>%
  set_engine("ets")
etsMMMN <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "multiplicative", damping = 'none') %>%
  set_engine("ets")
etsMMMD <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "multiplicative", damping = 'damped') %>%
  set_engine("ets")
ets_auto <- exp_smoothing(error = "auto",trend = "auto",season = "auto") %>%
    set_engine("ets")
smooth_etsANN <- exp_smoothing(error = "additive",trend = "none",season = "none") %>%
  set_engine("smooth_es")
smooth_etsANA <- exp_smoothing(error = "additive",trend = "none",season = "additive") %>%
  set_engine("smooth_es")
smooth_etsANM <- exp_smoothing(error= "additive",trend = "none",season = "multiplicative") %>% set_engine("smooth_es")
smooth_etsAAN <- exp_smoothing(error = "additive",trend = "additive",season = "none") %>%
  set_engine("smooth_es")
smooth_etsAAA <- exp_smoothing(error = "additive",trend = "additive",season = "additive") %>%
  set_engine("smooth_es")
smooth_etsAAM <- exp_smoothing(error = "additive",trend = "additive",season = "multiplicative") %>%
  set_engine("smooth_es")
smooth_etsAMN <- exp_smoothing(error = "additive",trend = "multiplicative",season = "none") %>%
  set_engine("smooth_es")
smooth_etsAMA <- exp_smoothing(error = "additive",trend = "multiplicative",season = "additive") %>%
  set_engine("smooth_es")
smooth_etsAMM <- exp_smoothing(error = "additive",trend = "multiplicative",season = "multiplicative") %>%
  set_engine("smooth_es")
smooth_etsMNN <- exp_smoothing(erro = "multiplicative",trend = "none",season = "none") %>%
  set_engine("smooth_es")
smooth_etsMNA <- exp_smoothing(erro = "multiplicative",trend = "none",season = "additive") %>%set_engine("smooth_es")
smooth_etsMNM <- exp_smoothing(error= "multiplicative",trend = "none",season = "multiplicative") %>% set_engine("smooth_es")
smooth_etsMAN <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "none") %>%
  set_engine("smooth_es")
smooth_etsMAA <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "additive") %>%
  set_engine("smooth_es")
smooth_etsMAM <- exp_smoothing(erro = "multiplicative",trend = "additive",season = "multiplicative") %>%
  set_engine("smooth_es")
smooth_etsMMN <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "none") %>%
  set_engine("smooth_es")
smooth_etsMMA <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "additive") %>%
  set_engine("smooth_es")
smooth_etsMMM <- exp_smoothing(erro = "multiplicative",trend = "multiplicative",season = "multiplicative") %>%
  set_engine("smooth_es")

smooth_ets_auto <- exp_smoothing(error = "auto",trend = "auto",season = "auto") %>%
  set_engine("smooth_es")
croston <- exp_smoothing() %>%
    set_engine("croston")
theta <-  exp_smoothing() %>%
    set_engine("theta")
```

```{r}
model_work2 <- workflow_set(
  preproc = list(
    base                  = recipe_base,
    features              = recipe_date_features, 
    extrafeatures         = recipe_date_extrafeatures,
    extrafeatures_lag     = recipe_date_extrafeatures_lag,
    extrafeatures_fourier = recipe_date_extrafeatures_fourier
  ),
  models  = list(
    M_croston           = croston,
    M_theta             = theta,
    ##M_etsauto           = ets_auto,
    ##M_smooth            = smooth_ets_auto,
    ##M_etsANN = etsANN,
    ##M_etsANA = etsANA,
    #M_etsANM = etsANM,
    ##M_etsAANN = etsAANN,
    ##M_etsAAND = etsAAND,
    ##M_etsAAAN = etsAAAN,
    ##M_etsAAAD = etsAAAD,
    #M_etsAAMN = etsAAMN,
    #M_etsAAMD = etsAAMD,
    #M_etsAMNN = etsAMNN,
    #M_etsAMND = etsAMND,
    #M_etsAMAN = etsAMAN,
    #M_etsAMAD = etsAMAD,
    #M_etsAMMN = etsAMMN,
    #M_etsAMMD = etsAMMD,
    #M_etsMNN = etsMNN,
    #M_etsMNA = etsMNA,
    ##M_etsMNM = etsMNM,
    M_etsMANN = etsMANN,
    M_etsMAND = etsMAND,
    ##M_etsMAAN = etsMAAN,
    ##M_etsMAAD = etsMAAD,
    ##M_etsMAMN = etsMAMN,
    ##M_etsMAMD = etsMAMD,
    ##M_etsMMNN = etsMANN,
    ##M_etsMMND = etsMMND,
    #M_etsMMAN = etsMMAN,
    #M_etsMMAD = etsMMAD,
    M_etsMMMN = etsMMMN,
    M_etsMMMD = etsMMMD,
    ##M_smooth_etsANN = smooth_etsANN,
    M_smooth_etsANA = smooth_etsANA,
    M_smooth_etsANM = smooth_etsANM,
    ##M_smooth_etsAAN = smooth_etsAAN,
    ##M_smooth_etsAAA = smooth_etsAAA,
    ##M_smooth_etsAAM = smooth_etsAAM,
    ##M_smooth_etsAMN = smooth_etsAMN,
    M_smooth_etsAMA = smooth_etsAMA,
    ##M_smooth_etsAMM = smooth_etsAMM,
    M_smooth_etsMNN = smooth_etsMNN,
    #M_smooth_etsMNA = smooth_etsMNA,
    M_smooth_etsMNM = smooth_etsMNM,
    M_smooth_etsMAN = smooth_etsMAN,
    M_smooth_etsMAA = smooth_etsMAA,
    ##M_smooth_etsMAM = smooth_etsMAM,
    M_smooth_etsMMN = smooth_etsMMN,
    M_smooth_etsMMA = smooth_etsMMA,
    M_smooth_etsMMM = smooth_etsMMM
  ),
  cross   = TRUE
)
model_fit2 <- modeltime_wfs_fit(.wfsets = model_work2, 
                            .split_prop = 0.8, 
                            .serie=df)

model_metrics2 <- modeltime_wfs_rank(model_fit2,
                              rank_metric = "rmse",
                              minimize = F)
model_metrics2 %>%
  select(-`.fit_model`) %>%
  mypdf1::pdf1_tbl("Métricas")
```


